---
global: {}

defaultAdminPassword: replaceme
timeZone: Eastern Standard Time # See `tzutil /l` output on windows for a list of possibilities
virtioContainerDiskVersion: v1.1.1
buildTimeout: 2h0m0s
winTenIsoDownloadUrl: ""
# winTenIsoDownloadUrl: https://s3.yourdomain.com/yourbucket/yourwin10.iso
postInstallPowershell: ""
template:
  cpuCores: 1
  memory: 4Gi
  diskSize: 20Gi
